version: "3"                    # ECS may not like decimal suffix"

# x-aws-logs_retention: 7          # ECS only
# x-aws-vpc: vpc-0eb412d8f43828513 # shentonfreude in ue1
# x-aws-vpc: vpc-2395654a         # UE2 default vpc (not default vpc in UE1)
#x-aws-vpc: vpc-087f3921182006a92  # UE1 vstudios-ecs I created non-default -- failed
x-aws-vpc: vpc-0b6188e87c0cdbb60 # UE1 vstudios-ecs "defaultish-vpc"

networks:
  # YELB says: user defined bridge required; default bridge network doesn't support name resolution
  flasknet:
    driver: bridge              # compose up to ECS: WARNING networks.driver: unsupported attribute

services:

  psql:
    container_name: psql
    image: postgres:9.6.2-alpine
    environment: 
      POSTGRES_USER:     flaskapp
      POSTGRES_DB:       flaskapp
      POSTGRES_PASSWORD: flaskapp
    healthcheck:
      test: "pg_isready --username=flaskapp && psql --username=flaskapp --list"
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - flasknet

  flaskapp:
    container_name: flaskapp
    # Must be an ECR tag for ECS to find the image
    # image: cshenton/flaskapp    # must tag with ECR name to push there
    image: ${AWS_ACCT}.dkr.ecr.${AWS_REGION}.amazonaws.com/cshenton/flaskapp:latest
    environment:
      # Neither bare service "psql",
      # FQDN "psql.psql.compose-ecs-flask-psql.local",
      # nor awsvpc "localhost" work.
      DB_HOST:     psql
      DB_PORT:     5432
      DB_NAME:     flaskapp
      DB_PASSWORD: flaskapp
      DB_USER:     flaskapp
    ports:
      - "80:80"
    depends_on:
      psql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    networks:
      - flasknet
