# ECS-specific features and customizations

x-aws-vpc: vpc-0af4ec9d6e4096f52 # vpc-defaulty in wp-dev in ue1

x-aws-logs_retention: 7

services:
  flaskapp:
    # Need a fully qualified name for ECR so ECS can pull it
    image: ${AWS_ACCT}.dkr.ecr.${AWS_REGION}.amazonaws.com/cshenton/flaskapp:latest
